version: '3.1'
services:
  nginx:
    container_name: some-nginx
    image: nginx
    restart: always
    ports:
      - 9090:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  docker-test1:
    image: novruz21/docker-test
    restart: always
    environment:
      DB_CONNECTION_IP: mysql
    ports:
      - 8080:8080
  docker-test2:
    image: novruz21/docker-test
    restart: always
    environment:
      DB_CONNECTION_IP: mysql
    ports:
      - 8081:8080

volumes:
  mysql_data:
