version: '3.1'
services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  docker-test:
    image: novruz21/docker-test
    restart: always
    environment:
      DB_CONNECTION_IP: mysql
    ports:
      - 9090:8080

volumes:
  mysql_data:
